load('v_data_full_data_with_profile.mat')

hold on

arrayfun(@(ind) ...
  plot(...
    rcell_u{ind} - rcell_u{ind}(1), ...
    Tcell{ind} - Tcell{ind}(1)...
    ), ...
  1:17, 'UniformOutput', false)