load('v_data')

figure
arrayfun(...
    @(index) ...
    VFile{index}.Tf(h, theta(index), VFile{index}.TotolTime),...
    1:length(VFile));
figure
arrayfun(...
    @(index) ...
    VFile{index}.Ug(h, theta(index), VFile{index}.TotolTime),...
    1:length(VFile));
figure
hold on
[rcell, Tcell] = arrayfun(...
    @(index) ...
    VFile{index}.T_r(h, theta(index), VFile{index}.TotolTime),...
    1:length(VFile),'UniformOutput',false);
arrayfun(@(r, T) plot(r{1}-r{1}(1), T{1}), rcell, Tcell);

figure
hold on
[rcell, Ucell] = arrayfun(...
    @(index) ...
    VFile{index}.U_r(h, theta(index), VFile{index}.TotolTime),...
    1:length(VFile),'UniformOutput',false);
arrayfun(@(r, U) plot(r{1}-r{1}(1), U{1}), rcell, Ucell);
[~, Tcell] = arrayfun(...
    @(index) ...
    VFile{index}.T_r(h, theta(index), VFile{index}.TotolTime),...
    1:length(VFile),'UniformOutput',false);
arrayfun(@(r, U) plot(r{1}-r{1}(1), U{1}), rcell, Ucell);

InteU = arrayfun(@(r, sU) trapz(r{1}, r{1}.*sU{1}), rcell, Ucell)';
InteT = arrayfun(@(r, sU) trapz(r{1}, r{1}.*(sU{1}-293.623)), rcell, Tcell)';
Uq = U.*theta.*(R+theta/2);
plot(Uq(1:end-1), -InteU(1:end-1), '-*');
axis([0 max(Uq(1:end-1)) 0 max(-InteU(1:end-1))]);

d_U = arrayfun(...
    @(index) ...
    VFile{index}.dv_R('av',h,VFile{index}.TotolTime),1:length(VFile))';